name: auto-update

on:
  repository_dispatch:
    types: update
  push:
    branches:
      - for-next
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  update-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        ssh-key: ${{ secrets.SSH_DEPLOY }}
    - name: follow for-next
      run: |
          git fetch origin for-next
          git merge --ff-only origin/for-next
    - uses: actions/setup-python@v2
    - name: Update tools
      run: python update-n-freeze.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.5.0
      with:
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit-message: "update tools"
        title: Next image
        assignees: pauleve
        branch: auto/next
        base: master
        body: |
            Candidate next image with updated tool versions.

            You can try it using
            ```
            colomoto-docker -V next
            ```

            By default, the image will be released on the first of next month.
            If you need a persistent tag before (e.g., for a finalized publication), please manifest yourself in a comment below or at https://gitter.im/colomoto/colomoto-docker and we will tag it right away.
