name: PR Docker image

on:
    pull_request:

jobs:
  validate:
    env:
      IMAGE: colomoto/colomoto-docker:pr${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        if: github.base_ref == 'for-next'
      - name: Docker image build
        if: github.base_ref == 'for-next'
        run: sh hooks/build
      - name: Docker image validation
        if: github.base_ref == 'for-next'
        run: docker run --rm $IMAGE env validate.sh
      - name: Login to docker hub
        if: github.base_ref == 'for-next'
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        if: github.base_ref == 'for-next'
        uses: actions-hub/docker@master
        with:
          args: push ${IMAGE}

