name: PR Docker image

on:
    pull_request_target:
      types: [opened, synchronize, reopened]
      branches:
        - 'for-next'

jobs:
  validate:
    env:
      IMAGE: ${{vars.COLOMOTO_DOCKER_IMAGE}}:pr${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Tools metadata
        run: |
          pip install -r hooks/requirements.txt
          python hooks/tools_metadata.py
      - name: Docker image build
        run: sh hooks/build
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        uses: actions-hub/docker@master
        with:
          args: push ${IMAGE}
      - name: Docker image validation
        run: docker run --rm $IMAGE env validate.sh
